[package]
name = "mesa"
version = "0.1.0"
compiler = "0.14.0"
entrypoint = "src/lib.typ"
authors = ["Davide G. F. Lombardo <davide.lombardo@eit.lth.se>"]
license = "MIT"
description = "Draw semiconductor devices and fabrication processes."
repository = "https://github.com/digiefel/mesa"
categories = ["visualization"]
disciplines = ["engineering", "physics"]
keywords = ["semiconductor", "visualization", "process-flow", "cetz"]
exclude = [
  "/.gitignore",
  "/manual.md",
  "/Cargo.lock",
  "/Cargo.toml",
  "/ROADMAP.md",
  "/assets/",
  "/crates/",
  "/examples/",
  "/scripts/",
  "/target/",
  "/tests/",
  "/vendor/",
]
